# Site settings
title: Desde Studio
email: hello@desdestudio.com

description: > # this means to ignore newlines until "baseurl:"
  Estudio de diseño, arte y comunicación. Ayudamos a trazar soluciones de negocio a través del diseño y la comunicación.

countries: México · Spain · UK

baseurl: /
url: "" # the base hostname & protocol for your site

logo: /assets/desde_logo_red.svg
img: /assets/desde-studio-card.jpg

include: ['_pages']
